// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdllgllugbewddylpqog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkbGxnbGx1Z2Jld2RkeWxwcW9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MDQyNTgsImV4cCI6MjA2NjQ4MDI1OH0.bASgi10-tcFqT4OHH4vM6UtlzGVbzRaZ8RycCbWnvoQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);